### ISSUE TITLE
Subgraph instance failed to run

### ISSUE THREAD

**Issue by sneg55** [GraphiteTools/compound-subgraph#3]
Subgraph instance failed to run: Failed to process trigger in block #10280653 (73d8484ea766adbe859d1527c44ab9049b28b1b17b62587b9642a2ce8c82cb6d), transaction ff144fd01c4084da2594b7ff9183c401f95c9143b342aa0d0793c5a7c400322c: Failed to invoke handler 'handleLiquidateBorrow': Mapping aborted at ~lib/@graphprotocol/graph-ts/index.ts, line 782, column 4, with message: Value is not a BigInt. wasm backtrace: 0: 0x13bd - <unknown>!<wasm function 63> 1: 0x13d1 - <unknown>!<wasm function 64> 2: 0x1876 - <unknown>!<wasm function 77> , code: SubgraphSyncingFailure, id:

**Comment by sneg55** [comment]
@Destiner

**Comment by Destiner** [comment]
Thanks @sneg55, fixed by adding USDT market.
